loki-stack:
  grafana:
    enabled: true
  prometheus:
    enabled: true
    alertmanager:
      persistentVolume:
        enabled: false
    server:
      persistentVolume:
        enabled: false
  fluent-bit:
    enabled: true
  promtail:
    enabled: false
